#!/bin/sh -e
#
# build docs

rm -fr docs

find site -type f | while read -r file; do
    dest=docs/${file#*/}

    mkdir -p "${dest%/*}"

    case ${file##*/} in
        *.*) cp -f "$file" "$dest" ;;
        *)   cat temp/a "$file" temp/b > "$dest.html" ;;
    esac
done

# printf lieu.cf > docs/CNAME
