#!/bin/sh -e
#
# generate blog index

cd site/blog; printf 'BLOG\n\n' > index

[ "$(find . -type f | wc -l)" -eq 1 ] && {
    printf 'No entries.\n' >> index; exit
}

find . -type f | grep -v 'index' | sort -r | while read -r blog; do
    set -- "$(sed q "$blog")" "$(sed 2q\;d "$blog")"

    printf '%s  %s\n' "$(date -d "${1##*  }" '+%F %R')" \
                      "<a href=${blog#*/}>${2##*  }</a>"
done >> index
