#!/bin/sh -e
#
# generate blog index

cd site; printf 'BLOG\n\n' > blog/index

find blog -type f | grep -v index | sort -r | while read -r blog; do
    set -- "$(sed q "$blog")" "$(sed 2q\;d "$blog")"

    printf '%s  %s\n' "$(date -d "${1##*  }" '+%F %R')" \
                      "<a href=/$blog>${2##*  }</a>"
done >> blog/index
